repos:
-   repo: https://github.com/PyCQA/isort.git
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--line-length", "120"]
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.1
    hooks:
      - id: ruff-format
        exclude: '^examples/|^tests/'
        args: [ "--line-length=120"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-yaml
        args: [--unsafe]
    -   id: debug-statements
-   repo: https://github.com/pycqa/flake8.git
    rev : 6.1.0
    hooks:
      - id: flake8
        args:
          - "--max-line-length=120"
          - "--max-complexity=18"
          - "--select=B,C,E,F,W,T4,B9"
          - "--ignore=E203,E266,E501,W503,F401,F403,F405,E402"
          - "--exclude=docs"
        files: ^src/pykiso
-   repo: https://github.com/commitizen-tools/commitizen.git
    rev: v2.20.4
    hooks:
      - id: commitizen
        stages: [commit-msg]
-   repo: https://github.com/codespell-project/codespell
    rev: v1.16.0
    hooks:
    -   id: codespell
        name: codespell
        description: Checks for common misspellings in text files.
        entry: codespell
        language: python
        types: [text]
